from enum import StrEnum


class UserRole(StrEnum):
    ADMIN = "ADMIN"
    AUDITOR = "AUDITOR"
    WORKSHOP = "WORKSHOP"


class CaseStatus(StrEnum):
    NUEVO = "NUEVO"
    PENDIENTE_DOCUMENTOS = "PENDIENTE_DOCUMENTOS"
    LISTO_PARA_AUDITORIA = "LISTO_PARA_AUDITORIA"
    EN_AUDITORIA = "EN_AUDITORIA"
    OBSERVADO = "OBSERVADO"
    APROBADO = "APROBADO"
    DENEGADO = "DENEGADO"
    REVISION_HUMANA = "REVISION_HUMANA"


class DocumentType(StrEnum):
    FACTURA = "FACTURA"
    ORDEN_REPARACION = "ORDEN_REPARACION"
    DETALLE_MANO_OBRA = "DETALLE_MANO_OBRA"
    FOTOS_DANIO = "FOTOS_DANIO"


class RuleType(StrEnum):
    PRECIO_MAXIMO = "PRECIO_MAXIMO"
    ITEM_DUPLICADO = "ITEM_DUPLICADO"
    ITEM_NO_RELACIONADO = "ITEM_NO_RELACIONADO"
    CANTIDAD_MAXIMA = "CANTIDAD_MAXIMA"
    DOCUMENTO_OBLIGATORIO = "DOCUMENTO_OBLIGATORIO"
    PORCENTAJE_VARIACION = "PORCENTAJE_VARIACION"


class RuleOperator(StrEnum):
    MAYOR_QUE = "MAYOR_QUE"
    MENOR_QUE = "MENOR_QUE"
    IGUAL_A = "IGUAL_A"
    DIFERENTE_DE = "DIFERENTE_DE"
    CONTIENE = "CONTIENE"
    NO_CONTIENE = "NO_CONTIENE"


class Severity(StrEnum):
    BAJA = "BAJA"
    MEDIA = "MEDIA"
    ALTA = "ALTA"
    CRITICA = "CRITICA"


class RuleStatus(StrEnum):
    ACTIVA = "ACTIVA"
    INACTIVA = "INACTIVA"
